### ISSUE TITLE
Unable to remove/uninstall

### ISSUE THREAD

**Issue by dayjobtitus** [jshackles/Enhanced_Steam_Standalone#25]
There seems to be no way to remove this once you run it once. Rebooting will lead to nothing connecting to the internet until you run the app again.

**Comment by jshackles** [comment]
Closing the application should set your system proxy settings back to default.  If this doesn't happen successfully, you can manually edit your proxy settings by opening Internet Explorer (as admin, if needed) and going to Tools -> Internet Options -> Connections -> LAN Settings and disabling the proxy there manually.
