### ISSUE TITLE
ESS seems to have caused blue screen.

### ISSUE THREAD

**Issue by bibbis** [jshackles/Enhanced_Steam_Standalone#27]
Here's exactly what happened:
I downloaded the Standalone version from here: http://www.enhancedsteam.com/standalone.
I closed my game (Neverwinter), closed Steam, then I unpacked ES, ran it, and then I opened Steam again to check out the new features.
After a while I decided that it was not for me, so I closed ES again.
Then I started Neverwinter again, and then I got a Blue Screen crash.

My system is around 6 months old, healthy and I have never had BS before.

After my PC started again, I noticed that I now had network issues.
Steam ran fine (connected online to the friends service etc.) but Chrome and my email software were both complaining about "proxy server" issues. I don't know what this is.

I restarted my PC again, but there was no difference.

Then I googled "enhanced steam standalone windows 8.1 blue screen proxy error" (on my phone).
Found nothing relevant.
Eventually I found this thread: https://m.reddit.com/r/Steam/comments/281ah9/warning_about_the_standalone_enhanced_steam/

I don't know if that is at all relevant.
It made me wonder, so I opened ES again, and as soon as I did, my connection went back online and now it stays online even if I close ES again.

I am going to restart my PC again, after I post this message, and see what happens now.

But even if everything is "fine" again now, this is really worrying me since something else might be wrong that I am not noticing right now, so I would love to get a response on this please.

Thanks, brb.

**Comment by jshackles** [comment]
If your PC is unable to connect to the internet when Enhanced Steam Standalone is closed, open Internet Explorer.  From the menu select Tools -> Internet Options and click on the tab labelled Connections.  Click the box at the bottom that says "LAN Settings", then un-check the box that says "Use a proxy server for your LAN".  This will completely undo any changes that Enhanced Steam Standalone performs on your system automatically on your behalf.

**Comment by bibbis** [comment]
After the restart, I now have internet access right away without ES running.

**Comment by bibbis** [comment]
Did you just fucking close this issue without even addressing the blue screen?
Are you for real?

**Comment by jshackles** [comment]
The issue with the blue screen has nothing to do with this application and is likely caused by the game you launched afterwards.

Also please keep in mind that I'm offering this support to you at no cost and am under no obligation to help you.

**Comment by bibbis** [comment]
I am 100% aware that you are under no obligation to help me when I download and use your free software. I am not at all being "that guy" who is always demanding some sort of top quality customer service from freeware developers, so don't patronize me, please.

I am simply genuinely concerned about what your software did to my system, so excuse me for getting annoyed when you completely ignored my concern. Is that really so strange?

**Comment by bibbis** [comment]
I know perfectly well that system crashes can be very sporadic and sometimes seem to be caused by no reason at all even when the system is running normally and doing something that has worked fine in the past.

But I've been playing this game for months now and never even had the game crash on me, and certainly not caused any BLUE SCREENS, nor have my system showed any signs of issues since I built it, so come on man... You are NOT blaming this on the game...

Just like I have to accept that you owe me absolutely NOTHING, YOU have to accept that you DO have a responsibility to make sure that the software you distribute online isn't harmful, and you SHOULD take an interest in something as severe as blue screen issues.

But if you really just want to dismiss this and be completely sure that it's not in ANY WAY possible that you need to change something in your software so that this doesn't happen again to someone else, then I'm powerless to stop you.
